database:
  host: localhost
  port: 5432
  name: myapp_db
  user: dbuser
  password: dbpass123
  url: postgresql://dbuser:dbpass123@localhost:5432/myapp_db

redis:
  host: localhost
  port: 6379
  url: redis://localhost:6379/0

mongodb:
  host: mongo-cluster
  port: 27017
  database: myapp
  url: mongodb://user:pass@mongo-cluster:27017/myapp

app:
  secret_key: my-secret-key-12345
  debug: true
  allowed_hosts:
    - localhost
    - 127.0.0.1
