# Cppcheck Configuration
# C/C++ static analysis

enabled: false  # Not installed by default

# Check levels to enable
enable:
  - all

# Check levels to disable
disable: []

# File extensions to check
extensions:
  - '.c'
  - '.cpp'
  - '.cc'
  - '.cxx'
  - '.h'
  - '.hpp'

# Include paths
includes: []

# Define preprocessor macros
defines: []

# Suppress specific warnings
suppress:
  - 'missingIncludeSystem'  # Suppress system include warnings

# Language standard
std:
  - 'c++11'
  - 'c99'

# Platform assumptions
platform: 'unix64'

# Output format
output_format: xml

# Additional options
options:
  # Check for unused functions
  unused_functions: true

  # Check for uninitialized variables
  uninitvar: true

  # Maximum complexity
  max_complexity: 10

  # Maximum conditional depth
  max_ctok: 50
