# ESLint Configuration
# JavaScript and TypeScript linting

enabled: true

# Configuration file path (if using custom config)
config_file: null

# File extensions to check
extensions:
  - '.js'
  - '.jsx'
  - '.ts'
  - '.tsx'
  - '.mjs'

# Environments to enable
envs:
  - 'browser'
  - 'node'
  - 'es6'

# Global variables
globals:
  console: true
  process: true
  Buffer: true

# Rules to enable/disable
rules:
  # Possible Errors
  'no-console': 'off'
  'no-debugger': 'error'
  'no-unused-vars': 'error'

  # Best Practices
  'eqeqeq': 'error'
  'no-eval': 'error'
  'no-implied-eval': 'error'

  # Variables
  'no-undef': 'error'

  # Stylistic Issues
  'indent': ['error', 2]
  'quotes': ['error', 'single']
  'semi': ['error', 'always']

# Plugins to load
plugins: []

# Parser options
parser_options:
  ecma_version: 2020
  source_type: 'module'

# Settings
settings:
  react:
    version: 'detect'

# Ignore patterns
ignore_patterns:
  - 'node_modules/'
  - 'dist/'
  - 'build/'
  - '*.min.js'

# Maximum warnings before failing
max_warnings: 0
