# Flake8 Configuration
# Python style guide enforcement

enabled: true

# Maximum line length
max_line_length: 88

# Select specific error codes to check (empty = all)
select:
  - E    # PEP8 errors
  - F    # PyFlakes errors
  - W    # PEP8 warnings
  - C    # McCabe complexity
  - N    # PEP8-Naming

# Error codes to ignore
ignore:
  - E501  # Line too long (handled by max_line_length)
  - W503  # Line break before binary operator
  - C901  # Too complex

# Maximum complexity score
max_complexity: 10

# Count errors and warnings separately
count: true

# Show source code for each error
show_source: true

# Show PEP8 text for each error
show_pep8: false

# Paths to exclude
exclude:
  - .git
  - __pycache__
  - .pytest_cache
  - .tox
  - venv
  - .venv
  - node_modules

# File extensions to check
filename:
  - '*.py'
  - '*.pyi'

# Per-file ignores
per_file_ignores:
  __init__.py: F401  # Allow unused imports in __init__.py
  test_*.py: S101    # Allow assert statements in tests
