# Pylint Configuration
# Python code quality checker

enabled: true

# Python version to use for checks
py_version: '3.8'

# Output format
output_format: json

# Include message IDs in output
include_ids: true

# Include symbolic names in output
include_symbolic_names: true

# Files or directories to ignore
ignore:
  - CVs
  - venv
  - .venv
  - node_modules
  - __pycache__

# Files that match these patterns will be ignored
ignore_patterns:
  - '.*\.pyc$'
  - '__pycache__'
  - '\.git'

# Python files to analyze
py_files: ['*.py']

# Confidence levels for messages
confidence:
  - HIGH
  - CONTROL_FLOW
  - INFERENCE
  - INFERENCE_FAILURE
  - UNDEFINED

# Enable these checks (leave empty to use defaults)
enable: []

# Disable these checks
disable:
  - C0103     # Variable name doesn't conform to snake_case
  - C0114     # Missing module docstring
  - C0115     # Missing class docstring
  - C0116     # Missing function or method docstring
  - R0903     # Too few public methods
  - R0912     # Too many branches
  - R0915     # Too many statements
  - W0511     # TODO comments

# Maximum number of characters per line
max_line_length: 88

# Maximum number of arguments per function
max_args: 5

# Maximum number of local variables per function
max_locals: 15

# Maximum number of branches per function
max_branches: 12

# Maximum number of statements per function
max_statements: 50

# Maximum number of attributes per class
max_attributes: 20

# Minimum number of public methods per class
min_public_methods: 1

# Maximum complexity score
max_complexity: 10
