# Semgrep Configuration
# Multi-language static analysis

enabled: true

# Rules to run (empty = all)
rules:
  - 'security'      # Security vulnerabilities
  - 'performance'   # Performance issues
  - 'correctness'   # Logic errors
  - 'maintainability'  # Code maintainability
  - 'portability'   # Portability issues

# Languages to analyze (empty = auto-detect)
languages: []

# Severity levels to include
severity:
  - 'high'
  - 'medium'
  - 'low'
  - 'info'

# Confidence levels to include
confidence:
  - 'high'
  - 'medium'
  - 'low'

# Custom configuration file path
custom_config_path: null

# Exclude these paths
exclude:
  - '*/test_*'
  - '*/tests/*'
  - '*/venv/*'
  - '*/.venv/*'
  - '*/node_modules/*'
  - '*/__pycache__/*'
  - '*/.git/*'

# Include these paths (overrides exclude)
include: []

# Output format
output_format: json

# Maximum number of targets to scan
max_targets: 1000

# Timeout per rule (seconds)
timeout: 30

# Enable experimental features
experimental: false

# Custom rules directory
rules_dir: null

# Metrics collection
metrics: false

