# SonarQube Configuration
# Comprehensive code quality and security platform

enabled: false  # Disabled by default - requires SonarQube server setup

# SonarQube server configuration
server_url: "http://localhost:9000"  # SonarQube server URL
login: null                          # Authentication token (recommended over password)
password: null                       # Password (use token instead)
organization: null                   # Organization key for SonarCloud

# Project configuration
project_key: "static-analysis-agent" # Unique project identifier
project_name: "Static Analysis Agent" # Human-readable project name
project_version: "1.0"

# Language-specific settings
python_version: "3.8"                # Python version for analysis
java_binaries: "target/classes"      # Path to compiled Java classes
javascript_framework: null           # Framework detection (React, Angular, Vue)

# Analysis scope
sources: "."                         # Source directories (comma-separated)
tests: "tests"                       # Test directories (comma-separated)
exclusions:                          # Files/directories to exclude
  - "**/node_modules/**"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.min.js"
  - "**/vendor/**"
  - "**/.git/**"

# Coverage integration
coverage_reports:
  - "coverage.xml"
  - "coverage/lcov.info"

# Quality profiles
quality_profile:
  python: "Sonar way"
  javascript: "Sonar way"
  java: "Sonar way"

# Rules configuration
rules:
  # Enable/disable specific rules
  # Example: "python:S3776": "off"  # Cognitive complexity

# Additional properties
additional_properties:
  sonar.scm.disabled: "true"         # Disable SCM integration
  sonar.qualitygate.wait: "true"     # Wait for quality gate
  sonar.analysis.mode: "publish"     # Analysis mode

# Performance settings
threads: 4                           # Number of analysis threads
timeout: 3600                        # Analysis timeout in seconds
