import yaml

def generate_openapi_spec(endpoints):
    """Generates an OpenAPI spec from a list of endpoints."""
    spec = {
        "openapi": "3.0.0",
        "info": {
            "title": "My API",
            "version": "1.0.0",
            "description": "An API generated by the OpenAPI Spec Agent"
        },
        "paths": {}
    }

    for endpoint in endpoints:
        path = endpoint["path"]
        if path not in spec["paths"]:
            spec["paths"][path] = {}

        for method in endpoint["methods"]:
            spec["paths"][path][method.lower()] = {
                "responses": {
                    "200": {
                        "description": "Successful response"
                    }
                }
            }

    return yaml.dump(spec)
