source 'https://rubygems.org'

gem 'rails', '~> 7.0.4'
gem 'pg', '~> 1.4'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'redis', '~> 4.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
end