Here is the complete OpenAPI 3.0.0 specification in YAML format:

openapi: 3.0.0
info:
  title: My API
  description: This is my API
  version: 1.0.0

components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer

  requestBodies:
    userRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRequest'

  responses:
    201 Created:
      description: User created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserResponse'
    400 Bad Request:
      description: Invalid request data
      content:
        application/json:
          schema:
            type: object

paths:
  /users:
    post:
      summary: Create a new user
      description: Creates a new user with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        400:
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object

    get:
      summary: Get all users
      description: Returns a list of all users.
      responses:
        200:
          description: Users returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'

  /users/{id}:
    get:
      summary: Get a user by ID
      description: Returns a single user with the provided ID.
      responses:
        200:
          description: User returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        404:
          description: User not found