```yml
openapi: 3.0.0
info:
  title: User API
  description: API for managing users
  version: 1.0.0

paths:
  /users:
    get:
      summary: Retrieve all users
      responses:
        '200':
          description: List of users in JSON format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{user_id}:
    get:
      summary: Retrieve a user by ID
      description: Get details about the user with the specified ID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User data in JSON format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users:
    post:
      summary: Create a new user
      description: Add a new user to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
```

Please note that this is a basic OpenAPI specification and might need to be extended with additional details such as authentication, authorization, and error handling based on your specific application requirements.